### ISSUE TITLE
A possible licenses you could use

### ISSUE THREAD

**Issue by KieranP** [cesmoak/smokescreen#1]
"Taking suggestions on which license to use."

GPL is too restrictive in the sense that it limits who can use it (only other open source software).
MIT is too open, in that another company could take the source, change, and charge for it.

I recommend the Apache license. My understanding of it is people can use the code for free, commercial or non-commercial usage, but changes to it need to be open sourced, so they can't just change things, and sell the improved code.

**Comment by ghost** [comment]
What about the LGPL -- freedom respecting and all the other advantages of GPL but without the restriction of only GPL compatible software being able to use it.

Remember that all the GPL licenses allow commercial use of software licensed under the GPL. If that's the only reason for picking another license, then there is no reason at all.

**Comment by shellster** [comment]
I suggest the "New BSD License".  It permits unfettered modification of the source code, and commercial use, but it states that all source code must keep the copy right notice and license information intact.  That way, no one can ever claim ownership of your work, but they can modify it and use it to their heart's content.

**Comment by vidad** [comment]
Definitely not GPL. If you use any license that restricts commercial use, this can't succeed. But if this works... yipes. What a game changer.

**Comment by d235j** [comment]
I would recommend some sort of New BSD license. Though the GPL would work too, but if you want to, please use GPLv2+ or LGPL 2.1+ (some companies won't touch [L]GPLv3 with a ten-foot pole because of anti-tivoization provisions and patent restrictions).

**Comment by cesmoak** [comment]
Thanks for the suggestions, guys. I've ended up choosing the MIT license.
